services:
  manga-reader:
    build:
      context: https://github.com/Dcrispim/manga-reader.git#main
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3993
    image: manga-reader:latest
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3993
    ports:
      - "0.0.0.0:3993:3993"
    volumes:
      - D:/manga:/mnt/d/manga
      - D:/manga-xl:/mnt/d/manga-xl
    restart: unless-stopped
